-- Create a database named bookmarks owned by dunder-mifflin.
CREATE DATABASE bookmarks OWNER 'dunder-mifflin';

-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title VARCHAR(30) not null unique,
  url VARCHAR(50) not null,
  description text,
  rating integer not null
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('Medium', 'https://medium.com/', '', 4.5 ),
  ('HackerRank', 'https://www.hackerrank.com/', 'Coding challenges', 5),
  ('React', 'https://reactjs.org', 'Front End JavaSCript Framework', 4),
  ('Postgres', 'https://www.postgresql.org', 'Database Management System', 5),
  ('Homebrew', 'https://brew.sh/', 'Mac package manager', 5),
  ('National Geographic', 'https://www.nationalgeographic.com/', '', 4),
  ('Twitter', 'https://twitter.com', '', 3),
  ('Slack', 'https://slack.com', 'chatting platform', 4),
  ('The Atlantic', 'https://www.theatlantic.com/', 'Current Events', 3 ),
  ('Apple', 'https://apple.com', 'computer hardware and operating system', 5);